apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fullcycle-app
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - name: nginx
          image: gcr.io/PROJECT_ID/fullcycle-nginx
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "256Mi"

        - name: nodejs
          image: gcr.io/PROJECT_ID/fullcycle-node
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          env:
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DB_NAME
              value: "nodedb"